package lambdacaverns.world;

import java.util.LinkedList;

/**
 * This class manages the messages generated by the game/world to be
 * displayed on the screen for the player.
 */
public class Messages {
    private int maxMessages;
    private LinkedList<String> text;
    
    /**
     * Constructor
     * @param maxMessages   since there is only limited real estate on the
     *                      SCREEN for displaying messages, this provides a way
     *                      for the world to forget old messages that can no
     *                      longer be displayed.
     */
    public Messages(int maxMessages) {
        this.maxMessages = maxMessages;
        this.text = new LinkedList<String>();
    }

    /**
     * Adds a message. This may be of arbitrary length and will be wrapped
     * by the user interface code.
     */
    public void add(String msg) {
        assert msg != null;
        if (text.size()  >= maxMessages) {
            text.removeFirst();
        }
        text.addLast(msg);
    }
    
    /**
     * @return a clone of the messages.
     */
    @SuppressWarnings("unchecked")
    public LinkedList<String> getTextList() {
        return (LinkedList<String>) text.clone();
    }
}
