/*
 * Caverns of Lambda - A Rogue-like
 * Copyright (C) 2014-2015  Ben Humphreys
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */
package lambdacaverns.world;

import java.util.LinkedList;
import java.util.List;

/**
 * This class manages the messages generated by the game/world to be
 * displayed on the screen for the player.
 */
public class Messages {
    private final int maxMessages;
    private final LinkedList<String> text;

    /**
     * Constructor
     *
     * @param maxMessages since there is only limited real estate on the
     *                    SCREEN for displaying messages, this provides a way
     *                    for the world to forget old messages that can no
     *                    longer be displayed.
     */
    public Messages(int maxMessages) {
        this.maxMessages = maxMessages;
        this.text = new LinkedList<>();
    }

    /**
     * Adds a message. This may be of arbitrary length and will be wrapped
     * by the user interface code.
     */
    public void add(String msg) {
        assert msg != null;
        if (text.size() >= maxMessages) {
            text.removeFirst();
        }
        text.addLast(msg);
    }

    /**
     * @return a clone of the messages.
     */
    @SuppressWarnings("unchecked")
    public List<String> getTextList() {
        return (List<String>) text.clone();
    }
}
